
DROP ROLE C##GESTOR_USUARIOS;
DROP ROLE C##GESTOR_RESERVAS;
DROP ROLE C##GESTOR_VUELOS;

----------------------------------------Creacion de roles-----------------------------------------------------------
CREATE ROLE C##GESTOR_USUARIOS;
CREATE ROLE C##GESTOR_RESERVAS;
CREATE ROLE C##GESTOR_VUELOS;

----------------------------------------Añadiendo privilegios a los roles-----------------------------------------------------------
GRANT ALL ON USUARIO TO C##GESTOR_USUARIOS;
GRANT  SELECT ON USUARIO TO C##GESTOR_RESERVAS;

GRANT ALL ON CUENTA_MILLA TO C##GESTOR_USUARIOS;
GRANT SELECT,UPDATE ON CUENTA_MILLA TO C##GESTOR_RESERVAS;

GRANT ALL ON TIPO_PAGO_TARJETA_CREDITO TO C##GESTOR_USUARIOS;
GRANT SELECT ON TIPO_PAGO_TARJETA_CREDITO TO C##GESTOR_RESERVAS;

GRANT ALL ON TIPO_PAGO_TARJETA_DEBITO TO C##GESTOR_USUARIOS;
GRANT SELECT ON TIPO_PAGO_TARJETA_DEBITO TO C##GESTOR_RESERVAS;

GRANT SELECT ON RESERVA_USUARIO TO C##GESTOR_USUARIOS;
GRANT ALL ON RESERVA_USUARIO TO C##GESTOR_RESERVAS;

GRANT SELECT ON RESERVA_USUARIO_AUTOMOVIL TO C##GESTOR_USUARIOS;
GRANT ALL ON RESERVA_USUARIO_AUTOMOVIL TO C##GESTOR_RESERVAS;

GRANT SELECT ON MARCA TO C##GESTOR_RESERVAS;

GRANT SELECT ON MODELO_AUTO TO C##GESTOR_RESERVAS;

GRANT SELECT ON MODELO_AUTO_OFICINA TO C##GESTOR_RESERVAS;

GRANT SELECT ON RENTADORA TO C##GESTOR_RESERVAS;

GRANT SELECT ON OFICINA TO C##GESTOR_RESERVAS;

GRANT SELECT ON RESERVA_USUARIO_HABITACION TO C##GESTOR_USUARIOS;
GRANT ALL ON RESERVA_USUARIO_HABITACION TO C##GESTOR_RESERVAS;

GRANT SELECT ON HABITACION TO C##GESTOR_RESERVAS;

GRANT SELECT ON ESTATUS_HABITACION TO C##GESTOR_RESERVAS;

GRANT SELECT ON TIPO_HABITACION TO C##GESTOR_RESERVAS;

GRANT SELECT ON HOTEL TO C##GESTOR_RESERVAS;

GRANT SELECT ON SEGURO TO C##GESTOR_RESERVAS;

GRANT SELECT ON SERVICIO TO C##GESTOR_RESERVAS;

GRANT SELECT ON SERVICIO_SEGURO TO C##GESTOR_RESERVAS;

GRANT SELECT ON ASEGURADORA TO C##GESTOR_RESERVAS;

GRANT ALL ON PAGO TO C##GESTOR_RESERVAS;

GRANT SELECT ON FACTURA_RESERVA TO C##GESTOR_USUARIOS;
GRANT ALL ON FACTURA_RESERVA TO C##GESTOR_RESERVAS;

GRANT ALL ON ESTATUS_FACTURA_RESERVA TO C##GESTOR_RESERVAS;

GRANT SELECT ON RESERVA_USUARIO_VUELO TO C##GESTOR_USUARIOS;
GRANT ALL ON RESERVA_USUARIO_VUELO TO C##GESTOR_RESERVAS;
GRANT SELECT ON RESERVA_USUARIO_VUELO TO C##GESTOR_VUELOS;

GRANT SELECT ON VUELO TO C##GESTOR_RESERVAS;
GRANT ALL ON VUELO TO C##GESTOR_VUELOS;

GRANT SELECT ON ESTATUS_VUELO TO C##GESTOR_RESERVAS;
GRANT ALL ON ESTATUS_VUELO TO C##GESTOR_VUELOS;

GRANT SELECT ON MODELO_AVION_AEROLINEA TO C##GESTOR_RESERVAS;
GRANT SELECT ON MODELO_AVION_AEROLINEA TO C##GESTOR_VUELOS;

GRANT SELECT ON AEROLINEA TO C##GESTOR_RESERVAS;
GRANT SELECT ON AEROLINEA TO C##GESTOR_VUELOS;

GRANT SELECT ON AEROLINEA_TIPO_AEROLINEA TO C##GESTOR_RESERVAS;
GRANT SELECT ON AEROLINEA_TIPO_AEROLINEA TO C##GESTOR_VUELOS;

GRANT SELECT ON TIPO_AEROLINEA TO C##GESTOR_RESERVAS;
GRANT SELECT ON TIPO_AEROLINEA TO C##GESTOR_VUELOS;

GRANT SELECT ON MODELO_AVION TO C##GESTOR_RESERVAS;
GRANT SELECT ON MODELO_AVION TO C##GESTOR_VUELOS;

GRANT SELECT ON AVION TO C##GESTOR_RESERVAS;
GRANT SELECT ON AVION TO C##GESTOR_VUELOS;

GRANT SELECT ON MODELO_AVION_CLASE TO C##GESTOR_RESERVAS;
GRANT SELECT ON MODELO_AVION_CLASE TO C##GESTOR_VUELOS;

GRANT SELECT ON CLASE TO C##GESTOR_RESERVAS;
GRANT SELECT ON CLASE TO C##GESTOR_VUELOS;

GRANT SELECT ON CUENTA_MILLA_VUELO TO C##GESTOR_USUARIOS;
GRANT ALL ON CUENTA_MILLA_VUELO TO C##GESTOR_RESERVAS;
GRANT SELECT ON CUENTA_MILLA_VUELO TO C##GESTOR_VUELOS;

GRANT SELECT ON AEROPUERTO TO C##GESTOR_RESERVAS;
GRANT SELECT ON AEROPUERTO TO C##GESTOR_VUELOS;

GRANT SELECT ON LUGAR TO C##GESTOR_RESERVAS;
GRANT SELECT ON LUGAR TO C##GESTOR_VUELOS;

GRANT SELECT ON ESTATUS TO C##GESTOR_RESERVAS;
GRANT SELECT ON ESTATUS TO C##GESTOR_VUELOS;

----------------------------------------Creacion de los usuarios-----------------------------------------------------------
DROP USER C##luis CASCADE;
DROP USER C##diego CASCADE;
DROP USER C##gabriel CASCADE;

CREATE USER C##luis IDENTIFIED BY 1234 DEFAULT TABLESPACE system;
CREATE USER C##diego IDENTIFIED BY 1234 DEFAULT TABLESPACE system;
CREATE USER C##gabriel IDENTIFIED BY 1234 DEFAULT TABLESPACE system;

GRANT CREATE SESSION TO C##GESTOR_USUARIOS;
GRANT CREATE SESSION TO C##GESTOR_RESERVAS;
GRANT CREATE SESSION TO C##GESTOR_VUELOS;
----------------------------------------Añadiendo a los usuarios los roles-----------------------------------------------------------

GRANT C##GESTOR_USUARIOS TO C##luis;
GRANT C##GESTOR_RESERVAS TO C##diego;
GRANT C##GESTOR_VUELOS TO C##gabriel;